# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ygcho/Desktop/school/graduate/simple_msp_gcs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ygcho/Desktop/school/graduate/simple_msp_gcs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ygcho/Desktop/school/graduate/simple_msp_gcs/CMakeFiles /home/ygcho/Desktop/school/graduate/simple_msp_gcs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ygcho/Desktop/school/graduate/simple_msp_gcs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simple_msp_gcs

# Build rule for target.
simple_msp_gcs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple_msp_gcs
.PHONY : simple_msp_gcs

# fast build rule for target.
simple_msp_gcs/fast:
	$(MAKE) -f CMakeFiles/simple_msp_gcs.dir/build.make CMakeFiles/simple_msp_gcs.dir/build
.PHONY : simple_msp_gcs/fast

msp_protocol/msp_protocol.o: msp_protocol/msp_protocol.cpp.o

.PHONY : msp_protocol/msp_protocol.o

# target to build an object file
msp_protocol/msp_protocol.cpp.o:
	$(MAKE) -f CMakeFiles/simple_msp_gcs.dir/build.make CMakeFiles/simple_msp_gcs.dir/msp_protocol/msp_protocol.cpp.o
.PHONY : msp_protocol/msp_protocol.cpp.o

msp_protocol/msp_protocol.i: msp_protocol/msp_protocol.cpp.i

.PHONY : msp_protocol/msp_protocol.i

# target to preprocess a source file
msp_protocol/msp_protocol.cpp.i:
	$(MAKE) -f CMakeFiles/simple_msp_gcs.dir/build.make CMakeFiles/simple_msp_gcs.dir/msp_protocol/msp_protocol.cpp.i
.PHONY : msp_protocol/msp_protocol.cpp.i

msp_protocol/msp_protocol.s: msp_protocol/msp_protocol.cpp.s

.PHONY : msp_protocol/msp_protocol.s

# target to generate assembly for a file
msp_protocol/msp_protocol.cpp.s:
	$(MAKE) -f CMakeFiles/simple_msp_gcs.dir/build.make CMakeFiles/simple_msp_gcs.dir/msp_protocol/msp_protocol.cpp.s
.PHONY : msp_protocol/msp_protocol.cpp.s

serial_setup/serial_setup.o: serial_setup/serial_setup.cpp.o

.PHONY : serial_setup/serial_setup.o

# target to build an object file
serial_setup/serial_setup.cpp.o:
	$(MAKE) -f CMakeFiles/simple_msp_gcs.dir/build.make CMakeFiles/simple_msp_gcs.dir/serial_setup/serial_setup.cpp.o
.PHONY : serial_setup/serial_setup.cpp.o

serial_setup/serial_setup.i: serial_setup/serial_setup.cpp.i

.PHONY : serial_setup/serial_setup.i

# target to preprocess a source file
serial_setup/serial_setup.cpp.i:
	$(MAKE) -f CMakeFiles/simple_msp_gcs.dir/build.make CMakeFiles/simple_msp_gcs.dir/serial_setup/serial_setup.cpp.i
.PHONY : serial_setup/serial_setup.cpp.i

serial_setup/serial_setup.s: serial_setup/serial_setup.cpp.s

.PHONY : serial_setup/serial_setup.s

# target to generate assembly for a file
serial_setup/serial_setup.cpp.s:
	$(MAKE) -f CMakeFiles/simple_msp_gcs.dir/build.make CMakeFiles/simple_msp_gcs.dir/serial_setup/serial_setup.cpp.s
.PHONY : serial_setup/serial_setup.cpp.s

simple_msp_gcs.o: simple_msp_gcs.cpp.o

.PHONY : simple_msp_gcs.o

# target to build an object file
simple_msp_gcs.cpp.o:
	$(MAKE) -f CMakeFiles/simple_msp_gcs.dir/build.make CMakeFiles/simple_msp_gcs.dir/simple_msp_gcs.cpp.o
.PHONY : simple_msp_gcs.cpp.o

simple_msp_gcs.i: simple_msp_gcs.cpp.i

.PHONY : simple_msp_gcs.i

# target to preprocess a source file
simple_msp_gcs.cpp.i:
	$(MAKE) -f CMakeFiles/simple_msp_gcs.dir/build.make CMakeFiles/simple_msp_gcs.dir/simple_msp_gcs.cpp.i
.PHONY : simple_msp_gcs.cpp.i

simple_msp_gcs.s: simple_msp_gcs.cpp.s

.PHONY : simple_msp_gcs.s

# target to generate assembly for a file
simple_msp_gcs.cpp.s:
	$(MAKE) -f CMakeFiles/simple_msp_gcs.dir/build.make CMakeFiles/simple_msp_gcs.dir/simple_msp_gcs.cpp.s
.PHONY : simple_msp_gcs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... simple_msp_gcs"
	@echo "... msp_protocol/msp_protocol.o"
	@echo "... msp_protocol/msp_protocol.i"
	@echo "... msp_protocol/msp_protocol.s"
	@echo "... serial_setup/serial_setup.o"
	@echo "... serial_setup/serial_setup.i"
	@echo "... serial_setup/serial_setup.s"
	@echo "... simple_msp_gcs.o"
	@echo "... simple_msp_gcs.i"
	@echo "... simple_msp_gcs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

